### PR TITLE
Refactor/as 3073 modify mint with sacd event order

### PR DESCRIPTION
**Pull request by LorranSutter**

### CODE REVIEW

**Review by elffjs — APPROVED** [review]

**Comment by elffjs** [comment]
Looks good to me. Let's try on dev real quick?

**Comment by LorranSutter** [comment]
> Looks good to me. Let's try on dev real quick?

It is already deployed on Amoy

**Comment by elffjs** [comment]
Let's mint something, let's see it, let's see it in Identity.

**Comment by LorranSutter** [comment]
https://amoy.polygonscan.com/tx/0xc8708b2399538db76d3d9d4b7762848a0e938de16a62ffa7d3a16cdd82da73f5

**Comment by elffjs** [comment]
Okay the SACD address held by the Vehicle NFT was wrong on dev. I think I fixed that. Can we do it again?

**Comment by elffjs** [comment]
Prod prod prod

**Pull request merged**
